In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [2]:
digit_data=tf.keras.datasets.mnist

In [3]:
(x_train,y_train),(x_test,y_test)=digit_data.load_data()

In [4]:
x_train.shape

(60000, 28, 28)

In [5]:
x_train=x_train/255
x_test=x_test/255

In [6]:
model=tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(units=128,activation='relu'),
    tf.keras.layers.Dense(units=128,activation='relu'),
    tf.keras.layers.Dense(units=10,activation='softmax'),
])

In [7]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [8]:
model.fit(x_train,y_train,epochs=3)

Epoch 1/3
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2304 - accuracy: 0.9323
Epoch 2/3
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1010 - accuracy: 0.9682
Epoch 3/3
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0701 - accuracy: 0.9779


In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 128)               100480    
                                                                 
 dense_1 (Dense)             (None, 128)               16512     
                                                                 
 dense_2 (Dense)             (None, 10)                1290      
                                                                 
Total params: 118,282
Trainable params: 118,282
Non-trainable params: 0
_________________________________________________________________


In [10]:
model.evaluate(x_test,y_test)

313/313 [==============================] - 0s 1ms/step - loss: 0.0879 - accuracy: 0.9726


[0.08790992200374603, 0.972599983215332]

In [24]:
pred=model.predict(x_test)

313/313 [==============================] - 1s 2ms/step


In [25]:
pred

array([[6.0217985e-08, 1.4267094e-07, 2.2052784e-05, ..., 9.9997413e-01,
        4.2331428e-07, 2.2454187e-06],
       [6.0443241e-11, 1.5566191e-05, 9.9998438e-01, ..., 3.7726572e-11,
        1.1921924e-08, 2.5396991e-13],
       [3.5817736e-06, 9.9386048e-01, 2.6136907e-04, ..., 4.1332829e-04,
        5.1046168e-03, 2.7980409e-06],
       ...,
       [1.1851401e-12, 1.5870451e-09, 2.0760669e-11, ..., 3.1681388e-06,
        2.4303775e-08, 3.7917475e-06],
       [2.8955617e-07, 2.0963077e-10, 1.6021315e-10, ..., 3.3336112e-10,
        6.3616120e-05, 1.3676288e-10],
       [4.2594706e-10, 8.1316325e-12, 1.9329203e-09, ..., 2.9843550e-15,
        2.2752604e-10, 5.3762556e-10]], dtype=float32)

In [19]:
x_test.shape

(10000, 28, 28)

In [28]:
x_test

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [29]:
pred1=model.predict(x_test[0].reshape(1,(28*28)))
pred1

1/1 [==============================] - 0s 18ms/step


array([[6.0218220e-08, 1.4267148e-07, 2.2052867e-05, 9.6282645e-07,
        1.0331239e-09, 8.2842586e-09, 4.5772620e-13, 9.9997413e-01,
        4.2331550e-07, 2.2454271e-06]], dtype=float32)

In [30]:
output=np.argmax(pred1)
output

7

In [31]:
y_test[0]

7

In [37]:
[layer0,layer1,layer2,layer3]=model.layers

In [42]:
w1,b1=layer1.get_weights()
w1.shape,b1.shape


((784, 128), (128,))

In [43]:
w1

array([[-0.00210391,  0.04293592,  0.0607402 , ...,  0.02843244,
        -0.02638707, -0.01025156],
       [ 0.04691888,  0.04483072, -0.02031357, ...,  0.03484236,
        -0.06412803,  0.00795659],
       [ 0.06870658, -0.01950204, -0.05619528, ...,  0.01935007,
         0.01364766,  0.06182794],
       ...,
       [ 0.06102618, -0.03333267,  0.07931969, ...,  0.02949534,
        -0.02131798, -0.02083075],
       [-0.00753486,  0.03074728, -0.05238571, ..., -0.01378347,
        -0.00649446, -0.05013729],
       [-0.01233509,  0.00812794,  0.02290165, ..., -0.04301451,
         0.06198902, -0.00215083]], dtype=float32)

In [44]:
b1

array([ 0.03678573, -0.00854668,  0.03291686,  0.00326475,  0.02882801,
        0.03842764, -0.01033636, -0.02590692,  0.04275075,  0.02857211,
       -0.02005202,  0.07294469,  0.00368551, -0.00432341, -0.0203963 ,
        0.0096529 ,  0.03213898,  0.0672378 ,  0.02917682, -0.0443019 ,
       -0.03034591, -0.00601856,  0.01127926,  0.04637001, -0.0161631 ,
       -0.0041377 , -0.01903386,  0.02078686,  0.01788306,  0.00815015,
        0.03299681,  0.02803469, -0.04443457,  0.00421833, -0.05858614,
       -0.07724669,  0.05919311, -0.01484247,  0.03163716,  0.00478456,
       -0.00785285,  0.0498717 ,  0.0390791 , -0.04300454, -0.06219972,
        0.00244221, -0.00660805, -0.05427959,  0.03178621, -0.012999  ,
        0.01310879, -0.04829749, -0.01165782,  0.03944688,  0.13751735,
        0.05831069, -0.03452552,  0.06860468,  0.11913384,  0.05189932,
        0.06229698, -0.04985052,  0.02405809,  0.04016732, -0.038481  ,
        0.02193066,  0.10298447,  0.04363297,  0.11477603,  0.02